### ISSUE TITLE
Migration to 14.0

### ISSUE THREAD

**Issue by sergiocorato** [sergiocorato/efatto#1]
- [x] ~analytic_show_invoice~ no more needed
- [x] ~analytic_show_sale~ no more needed
- [x] ~assets_management_report~ no more needed
- [x] auto_backup_healthcheck #15 
- [x] calendar_event_visibility #4 
- [x] ~calendar_task_work~ no more used
- [x] config_mrp #16 
- [x] config_sale #5
- [x] config_stock #17 
- [x] contacts_menu_visibility #6
- [x] contract_hr_rules #7 
- [x] ~contract_show_invoice_amount~ no more used
- [x] delivery_fix_price #18 
- [ ] hr_menu_employee_visibility
- [x] ir_attachment_visibility #10 
- [ ] l10n_it_central_journal_history
- [x] ~l10n_it_central_journal_subtotal~ funzione integrata nella stampa ufficiale
- [x] ~l10n_it_ddt_carrier~ no more needed
- [x] ~l10n_it_ddt_data~ no more needed
- [x] ~l10n_it_ddt_date_start~ no more needed
- [x] ~l10n_it_ddt_force_number~ sostituito da l10n_it_dn_force_number
- [x] l10n_it_ddt_force_number_done #59 (rinominato)
- [x] ~l10n_it_ddt_menu_in_out~ no more needed
- [x] ~l10n_it_ddt_menu_in_out_date_start~ no more needed
- [x] ~l10n_it_ddt_usability~ no more needed
- [x] l10n_it_dn_client_ref #21 
- [ ] l10n_it_dn_dropshipping
- [x] l10n_it_dn_force_number #41 
- [x] ~l10n_it_generic~ no more used
- [ ] l10n_it_payment_data
- [ ] l10n_it_reverse_charge_data
- [x] l10n_it_ricevute_bancarie_data #49 
- [ ] l10n_it_ricevute_bancarie_editable
- [ ] l10n_it_ricevute_bancarie_ext
- [x] l10n_it_ricevute_bancarie_total_report #19
- [x] ~l10n_it_vat_registries_report~ no more needed
- [x] mail_activity_open_origin #20 
- [x] mrp_sale_info_link #25 
- [x] mrp_sale_info_link_notes #26 
- [x] partner_history #37 
- [x] product_sellers_info #29
- [x] ~project_rules~ no more needed
- [x] project_stage_unique #11 
- [x] project_task_calendar #12
- [ ] project_task_freeze_partner
- [x] ~project_task_sale_line_update~ no more needed
- [x] project_task_state_color #13 
- [ ] purchase_comment_template_enable_editable
- [x] ~purchase_no_default_create_invoice~ no more needed
- [ ] purchase_request_procurement
- [x] purchase_state_tag #31 
- [ ] purchase_supplierinfo_update
- [x] ~sale_advance_invoice~ no more needed
- [x] ~sale_advance_invoice_sal~ no more needed
- [x] sale_bookmark #22 
- [ ] sale_comment_template_enable_editable
- [x] ~sale_delivered_percent~ no more needed
- [x] sale_order_auto_confirm #23 
- [x] sale_order_calendar_state #24 
- [x] sale_order_component_info #27 
- [ ] sale_order_product_policy
- [ ] sale_order_project_origin
- [x] sale_stats_days_custom #38 
- [x] sale_stock_lot_group #35 
- [x] sale_stock_mrp_produce_delay #28 
- [x] server_env #2 
- [ ] server_env_google_calendar
- [x] server_env_mail #3 
- [ ] stock_inventory_discrepancy_report_py3o
- [x] ~stock_inventory_valuation~ replaced
- [x] ~stock_inventory_valuation_report_py3o~ replaced
- [x] stock_lot_usability #53 
- [x] stock_move_available_date_expected #30 
- [x] stock_move_available_date_expected_mrp #33 
- [x] stock_move_details #32
- [ ] stock_move_details_picking_partner
- [x] stock_move_view_reserved #57 
- [x] stock_move_view_sale_purchase #54 
- [x] stock_orderpoint_generator_sale #36 
- [x] stock_picking_completed_assign #52 
- [ ] stock_picking_in_reference
- [x] stock_picking_update_move_price #51 
- [x] stock_procurement_draft_purchase #40 
- [x] stock_reserve_date_check #34 
- [ ] stock_rule_partner
- [x] stock_transfer_button #50 
- [ ] stock_unreserve_action

**Comment by sergiocorato** [comment]
- [x] ~account_analytic_line_tag~ no more used
- [x] account_analytic_menu #47 
- [ ] account_analytic_mrp_extra_cost
- [ ] account_analytic_project
- [x] ~account_analytic_sal~ no more used
- [ ] account_financial_report_group
- [ ] account_financial_report_landscape
- [x] account_invoice_constraint_chronology_supplier #8 
- [ ] account_invoice_move_view
- [x] account_invoice_supplierinfo_update_fix #48 
- [x] account_invoice_update_purchase #14 
- [ ] account_invoice_update_purchase_mrp
- [ ] account_invoice_update_purchase_on_weight
- [ ] account_payment_partner_readonly
- [ ] account_stock_price_unit_sync_analytic
